name: Android ktlint
on:
  push:
    branches:
      - fork
  pull_request:
    branches:
      - fork
  schedule:
    - cron:  '0 12 * * *' # Every day at 12 PM UTC
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: ktlint
